###########
# General #
###########

# NAME =
CXX = c++
CXXFLAGS = -std=c++98 -Wall -Wextra -Werror

# SRCS =
OBJS = $(addprefix $(OBJS_DIR)/, $(SRCS:%.cpp=%.o))
OBJS_DIR = ./objs

#################
# General Rules #
#################

.PHONY: all clean fclean re

